// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/todo.proto

package todo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Description          string               `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Due                  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Due,proto3" json:"Due,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=Created,proto3" json:"Created,omitempty"`
	DaysToComplete       int32                `protobuf:"varint,5,opt,name=DaysToComplete,proto3" json:"DaysToComplete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetDue() *timestamp.Timestamp {
	if m != nil {
		return m.Due
	}
	return nil
}

func (m *Item) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Item) GetDaysToComplete() int32 {
	if m != nil {
		return m.DaysToComplete
	}
	return 0
}

type Items struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=Offset,proto3" json:"Offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Items) Reset()         { *m = Items{} }
func (m *Items) String() string { return proto.CompactTextString(m) }
func (*Items) ProtoMessage()    {}
func (*Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{1}
}

func (m *Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Items.Unmarshal(m, b)
}
func (m *Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Items.Marshal(b, m, deterministic)
}
func (m *Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Items.Merge(m, src)
}
func (m *Items) XXX_Size() int {
	return xxx_messageInfo_Items.Size(m)
}
func (m *Items) XXX_DiscardUnknown() {
	xxx_messageInfo_Items.DiscardUnknown(m)
}

var xxx_messageInfo_Items proto.InternalMessageInfo

func (m *Items) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Items) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Items) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Items) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{2}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Pagination struct {
	Limit                int32    `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{3}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Pagination) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Item)(nil), "todo.Item")
	proto.RegisterType((*Items)(nil), "todo.Items")
	proto.RegisterType((*ID)(nil), "todo.ID")
	proto.RegisterType((*Pagination)(nil), "todo.Pagination")
	proto.RegisterType((*Empty)(nil), "todo.Empty")
}

func init() { proto.RegisterFile("pb/todo.proto", fileDescriptor_1f52905b89a1b23f) }

var fileDescriptor_1f52905b89a1b23f = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xdd, 0x4a, 0xf3, 0x40,
	0x10, 0x65, 0xd3, 0x6c, 0xdb, 0x6f, 0xc2, 0x57, 0x64, 0x29, 0x12, 0x72, 0xd3, 0x10, 0x41, 0x22,
	0x48, 0x0a, 0xd5, 0x2b, 0x6f, 0x1b, 0x91, 0x82, 0xa0, 0x2c, 0xf1, 0x01, 0x52, 0x3b, 0x2d, 0x81,
	0x6e, 0x37, 0x64, 0xa7, 0x42, 0x9f, 0xc5, 0xd7, 0xf1, 0xc1, 0x24, 0x9b, 0xf4, 0xc7, 0x22, 0x78,
	0x37, 0x73, 0xf6, 0xcc, 0x99, 0x39, 0x67, 0xe1, 0x7f, 0x39, 0x1f, 0x93, 0x5e, 0xe8, 0xa4, 0xac,
	0x34, 0x69, 0xe1, 0xd6, 0x75, 0x30, 0x5a, 0x69, 0xbd, 0x5a, 0xe3, 0xd8, 0x62, 0xf3, 0xed, 0x72,
	0x4c, 0x85, 0x42, 0x43, 0xb9, 0x2a, 0x1b, 0x5a, 0xf4, 0xc5, 0xc0, 0x9d, 0x11, 0x2a, 0x31, 0x00,
	0x67, 0x96, 0xfa, 0x2c, 0x64, 0xf1, 0x3f, 0xe9, 0xcc, 0x52, 0x11, 0x82, 0x97, 0xa2, 0x79, 0xaf,
	0x8a, 0x92, 0x0a, 0xbd, 0xf1, 0x1d, 0xfb, 0x70, 0x0a, 0x89, 0x5b, 0xe8, 0xa4, 0x5b, 0xf4, 0x3b,
	0x21, 0x8b, 0xbd, 0x49, 0x90, 0x34, 0x9b, 0x92, 0xfd, 0xa6, 0x24, 0xdb, 0x6f, 0x92, 0x35, 0x4d,
	0xdc, 0x43, 0x6f, 0x5a, 0x61, 0x4e, 0xb8, 0xf0, 0xdd, 0x3f, 0x27, 0xf6, 0x54, 0x71, 0x0d, 0x83,
	0x34, 0xdf, 0x99, 0x4c, 0x4f, 0xb5, 0x2a, 0xd7, 0x48, 0xe8, 0xf3, 0x90, 0xc5, 0x5c, 0x9e, 0xa1,
	0x91, 0x02, 0x5e, 0xbb, 0x30, 0x22, 0x6c, 0x0b, 0x9f, 0x85, 0x9d, 0xd8, 0x9b, 0x40, 0x62, 0x23,
	0xa9, 0x21, 0xd9, 0x32, 0x86, 0xc0, 0x33, 0x4d, 0xf9, 0xda, 0x5a, 0xe2, 0xb2, 0x69, 0x6a, 0xf4,
	0xb9, 0x50, 0x05, 0x59, 0x3b, 0x5c, 0x36, 0x8d, 0xb8, 0x84, 0xee, 0xcb, 0x72, 0x69, 0x90, 0xec,
	0xcd, 0x5c, 0xb6, 0x5d, 0x34, 0xac, 0xc3, 0x3a, 0x8f, 0x2c, 0x7a, 0x00, 0x78, 0xcd, 0x57, 0xc5,
	0x26, 0xb7, 0xf1, 0x1c, 0x14, 0xd9, 0xef, 0x8a, 0xce, 0x0f, 0xc5, 0x1e, 0xf0, 0x47, 0x55, 0xd2,
	0x6e, 0xf2, 0xc9, 0xc0, 0xcd, 0xf4, 0x42, 0x8b, 0x08, 0xe0, 0xad, 0x34, 0x58, 0x91, 0xfd, 0x9e,
	0x13, 0x23, 0x41, 0xbf, 0xad, 0x53, 0x71, 0x03, 0xfd, 0x27, 0xa4, 0xc6, 0xd7, 0x45, 0x83, 0x1e,
	0x2f, 0x08, 0xbc, 0xe3, 0x8c, 0x11, 0x23, 0xe8, 0xb5, 0x54, 0x71, 0x98, 0x0f, 0x4e, 0x54, 0xc5,
	0x15, 0x80, 0x44, 0xa5, 0x3f, 0xf0, 0x8c, 0xd3, 0xaa, 0xd8, 0xeb, 0xe6, 0x5d, 0xfb, 0x59, 0x77,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x1e, 0x85, 0x9a, 0x6d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoClient is the client API for Todo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoClient interface {
	UpsertItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*ID, error)
	GetItems(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*Items, error)
	GetItem(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Item, error)
	RemoveItem(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error)
}

type todoClient struct {
	cc *grpc.ClientConn
}

func NewTodoClient(cc *grpc.ClientConn) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) UpsertItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*ID, error) {
	out := new(ID)
	err := c.cc.Invoke(ctx, "/todo.Todo/UpsertItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) GetItems(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*Items, error) {
	out := new(Items)
	err := c.cc.Invoke(ctx, "/todo.Todo/GetItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) GetItem(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/todo.Todo/GetItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) RemoveItem(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/todo.Todo/RemoveItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServer is the server API for Todo service.
type TodoServer interface {
	UpsertItem(context.Context, *Item) (*ID, error)
	GetItems(context.Context, *Pagination) (*Items, error)
	GetItem(context.Context, *ID) (*Item, error)
	RemoveItem(context.Context, *ID) (*Empty, error)
}

// UnimplementedTodoServer can be embedded to have forward compatible implementations.
type UnimplementedTodoServer struct {
}

func (*UnimplementedTodoServer) UpsertItem(ctx context.Context, req *Item) (*ID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertItem not implemented")
}
func (*UnimplementedTodoServer) GetItems(ctx context.Context, req *Pagination) (*Items, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItems not implemented")
}
func (*UnimplementedTodoServer) GetItem(ctx context.Context, req *ID) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItem not implemented")
}
func (*UnimplementedTodoServer) RemoveItem(ctx context.Context, req *ID) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveItem not implemented")
}

func RegisterTodoServer(s *grpc.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_UpsertItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).UpsertItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Todo/UpsertItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).UpsertItem(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pagination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Todo/GetItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetItems(ctx, req.(*Pagination))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Todo/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetItem(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_RemoveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).RemoveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Todo/RemoveItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).RemoveItem(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertItem",
			Handler:    _Todo_UpsertItem_Handler,
		},
		{
			MethodName: "GetItems",
			Handler:    _Todo_GetItems_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _Todo_GetItem_Handler,
		},
		{
			MethodName: "RemoveItem",
			Handler:    _Todo_RemoveItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/todo.proto",
}
